version: '3.8'

services:
  web:
    build: .
    ports:
      - "${WEB_PORT_EXTERNAL}:${WEB_PORT_INTERNAL}"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - internal_net

  redis:
    image: redis:7-alpine
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge
