version: '3.8'

services:
  web:
    build: .
    ports:
      - "${WEB_PORT}:5000" 
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"
